spring:
  datasource:
    url: jdbc:h2:mem:todo # http://localhost:8080/h2-console
    username: user
  h2:
    console:
      enabled: true
  graphql:
    schema:
      introspection:
        enabled: true
    graphiql:
      enabled: true
